# (Documentation.Js Action, 2020/2022)
name: jsdoc
on:
 push:
   branches:
     - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: andstor/jsdoc-action@v1.2.1
      with:
        input: ./src
        output: ./jsdoc
